#!/bin/bash

# A helper script to download / install binary

set -e

DL=https://github.com/gilt/okta-aws-login/releases/download/v0.5
DL_BIN=$DL/okta-aws-login-$(uname -s)-$(uname -m)
TARGET=/usr/local/bin/okta-aws-login

echo "Downloading binary from $DL_BIN ..."
echo "You may be prompted for your local unix password by sudo"
sudo curl -L -o $TARGET $DL_BIN

curl -L -o /tmp/okta-aws-login.sig $DL_BIN.sig

if (type gpg) ; then
  echo "Downloading GPG pub key ..."
  gpg --keyserver keys.gnupg.net --recv-key 0x3C35F6BBA50B5999

  echo "Verifying signature ..."
  gpg --verify /tmp/okta-aws-login.sig $TARGET || { echo "GPG signature check failed!"; exit 1; }
else
  echo "GPG is not found on this system, continuing without signature verification, it's a good idea to install GPG and re-run the install script"
fi

echo "Making downloaded binary executable ..."
echo "You may be prompted for your local unix password by sudo"
sudo chmod 755 $TARGET

echo
echo
echo "Installed $TARGET"
echo "Please make sure it's in your shell PATH"
echo "Please download okta-aws-login.json config provided by your SAs and save it to $HOME/.okta-aws-login.json"
