name: okta-aws-login
version: '0.1.0.0'
synopsis: CLI to login to AWS accounts with Okta SSO.
description: Please see README.md
category: Web
author: Author name here
maintainer: example@example.com
copyright: 2016 Author name here
license: BSD3
homepage: https://github.com/EarnestResearch/okta-aws-login

data-files:
  - data/*

ghc-options:
  - -Wall
  - -Werror

dependencies:
  - aeson
  - aeson-casing
  - aeson-pretty
  - amazonka-core
  - amazonka-ecr
  - amazonka-sts
  - ansi-wl-pprint
  - base
  - base64-bytestring
  - bytestring
  - conduit
  - conduit-extra
  - containers
  - control-bool
  - directory
  - exceptions
  - filepath
  - gitrev
  - http-client
  - http-conduit
  - http-types
  - ini
  - lens
  - lens-aeson
  - monad-control
  - monad-logger
  - monad-loops
  - mtl
  - optparse-applicative
  - process
  - tagsoup
  - text
  - text-conversions
  - time
  - transformers
  - transformers-base
  - unordered-containers
  - utf8-string
  - xml-conduit
  - xml-lens

library:
  source-dirs: src

executables:
  okta-aws-login:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
    dependencies:
      - okta-aws-login

tests:
  okta-aws-login-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - HUnit
      - hspec
      - okta-aws-login
    build-tools:
      - hspec-discover
